# Pertemuan 4 — Data Cleaning dan Exploratory Data Analysis

Dataset yang sama dengan pertemuan 3 (`data.csv`), tapi sekarang kita bersihin.

## NumPy vs Pandas: Recap Singkat

Sesi membahas Pandas bersihin data (`drop_duplicates`, `fillna`, `to_datetime`) dan meringkasnya (`groupby`, `agg`, `pivot_table`). Untuk data visualisasi hanya akan dibahas di pertemuan 5 saja.

## 0. Sebelum ke Dataset Asli: Kenalan Dulu Sama Perintahnya

Data Cleaning itu bersihin data (buang duplikat, isi yang kosong, benerin tipe data, cek outlier) sebelum dipakai buat apa-apa.

EDA itu langkah sesudahnya — data yang udah bersih diringkas biar ketauan ceritanya (`groupby`, `agg`, `pivot_table`).

Urutannya selalu sama: beresin dulu datanya, baru gali insight-nya. Kalau kebalik, hasil ringkasannya masih kena efek data yang berantakan.

Biar kebayang gunanya masing-masing perintah, coba dulu di tabel kecil (`toy`, 6 baris, sengaja dibikin berantakan) — tiap perintah ditunjukin hasil **sebelum** dan **sesudah**, baru abis itu dipakai ke `data.csv` yang beneran.

In [1]:
import pandas as pd

toy = pd.DataFrame({
    "id": [1, 2, 3, 4, 4, 5],
    "tanggal": ["2026-01-01", "2026-01-05", "31-02-2026", "2026-02-10", "2026-02-10", "2026-03-01"],
    "kategori": ["A", "B", "A", "B", "B", "A"],
    "harga": ["100000", "abc", "250000", "300000", "300000", "5000000"],
})
display(toy)

   id     tanggal kategori    harga
0   1  2026-01-01        A   100000
1   2  2026-01-05        B      abc
2   3  31-02-2026        A   250000
3   4  2026-02-10        B   300000
4   4  2026-02-10        B   300000
5   5  2026-03-01        A  5000000

### Buang duplikat: `drop_duplicates()`

Baris id 4 muncul 2 kali persis sama. Kalau dibiarkan, nanti pas dijumlahkan jadi kehitung dobel.

In [2]:
print("Sebelum, jumlah baris:", toy.shape[0])

toy = toy.drop_duplicates()

print("Sesudah, jumlah baris:", toy.shape[0])
display(toy)

Sebelum, jumlah baris: 6
Sesudah, jumlah baris: 5

   id     tanggal kategori    harga
0   1  2026-01-01        A   100000
1   2  2026-01-05        B      abc
2   3  31-02-2026        A   250000
3   4  2026-02-10        B   300000
5   5  2026-03-01        A  5000000

### Benerin tipe data: `to_numeric()` / `to_datetime()`

Kolom `harga` sama `tanggal` sebenarnya harusnya angka dan tanggal, tapi kebaca sebagai teks biasa. Ada juga nilai yang formatnya rusak (`"abc"`, `"31-02-2026"`) — pakai `errors="coerce"` biar yang rusak itu jadi kosong aja, bukan bikin error.

In [3]:
print("Sebelum:")
print(toy.dtypes)

toy["harga"] = pd.to_numeric(toy["harga"], errors="coerce")
toy["tanggal"] = pd.to_datetime(toy["tanggal"], errors="coerce")

print("\nSesudah:")
print(toy.dtypes)
display(toy)

Sebelum:
id           int64
tanggal     object
kategori    object
harga       object
dtype: object

Sesudah:
id                   int64
tanggal     datetime64[ns]
kategori            object
harga              float64
dtype: object

   id    tanggal kategori      harga
0   1 2026-01-01        A   100000.0
1   2 2026-01-05        B        NaN
2   3        NaT        A   250000.0
3   4 2026-02-10        B   300000.0
5   5 2026-03-01        A  5000000.0

### Kalau data kosong dihapus: `dropna()`

Ini contoh kalau kita PILIH buat menghapus baris yang ada kosongnya — bukan yang bakal dipakai, cuma dicoba dulu biar keliatan efeknya.

In [4]:
print("Sebelum:")
display(toy)

print("Kalau dropna:")
display(toy.dropna())

Sebelum:

   id    tanggal kategori      harga
0   1 2026-01-01        A   100000.0
1   2 2026-01-05        B        NaN
2   3        NaT        A   250000.0
3   4 2026-02-10        B   300000.0
5   5 2026-03-01        A  5000000.0

Kalau dropna:

   id    tanggal kategori      harga
0   1 2026-01-01        A   100000.0
3   4 2026-02-10        B   300000.0
5   5 2026-03-01        A  5000000.0

### Isi data kosong: fillna()

Harga yang kosong diisi pakai median dari harga yang lain — masih masuk akal ditebak.

Tanggal beda kasus: gak ada tanggal yang bisa ditebak dengan masuk akal, jadi dibiarin NaT aja (versi "kosong" punya tanggal). Cukup dicatat berapa banyak yang kosong.

In [5]:
print("Sebelum:")
display(toy)

print("Jumlah kosong per kolom:")
print(toy.isna().sum())

toy["harga"] = toy["harga"].fillna(toy["harga"].median())

print("Sesudah (harga diisi, tanggal dibiarin NaT):")
display(toy)

Sebelum:

   id    tanggal kategori      harga
0   1 2026-01-01        A   100000.0
1   2 2026-01-05        B        NaN
2   3        NaT        A   250000.0
3   4 2026-02-10        B   300000.0
5   5 2026-03-01        A  5000000.0

Jumlah kosong per kolom:
id          0
tanggal     1
kategori    0
harga       1
dtype: int64
Sesudah (harga diisi, tanggal dibiarin NaT):

   id    tanggal kategori      harga
0   1 2026-01-01        A   100000.0
1   2 2026-01-05        B   275000.0
2   3        NaT        A   250000.0
3   4 2026-02-10        B   300000.0
5   5 2026-03-01        A  5000000.0

### Outlier: aturan IQR

Ada 2 harga yang kelewat jauh dari yang lain (100.000 dan 5.000.000). Coba lihat efeknya ke rata-rata sebelum dan sesudah dibuang.

In [6]:
print("Sebelum, rata-rata harga:", toy["harga"].mean())

q1, q3 = toy["harga"].quantile(0.25), toy["harga"].quantile(0.75)
iqr = q3 - q1
batas_bawah, batas_atas = q1 - 1.5 * iqr, q3 + 1.5 * iqr
toy = toy[(toy["harga"] >= batas_bawah) & (toy["harga"] <= batas_atas)]

print("Sesudah, rata-rata harga:", toy["harga"].mean())
display(toy)

Sebelum, rata-rata harga: 1185000.0
Sesudah, rata-rata harga: 275000.0

   id    tanggal kategori     harga
1   2 2026-01-05        B  275000.0
2   3        NaT        A  250000.0
3   4 2026-02-10        B  300000.0

### Ringkas per kelompok: `groupby()` + `agg()` + `sort_values()`

Ini udah masuk EDA — datanya sudah bersih dari langkah-langkah di atas, sekarang diringkas per kategori.

In [7]:
print("Sebelum diringkas:")
display(toy[["kategori", "harga"]])

ringkasan_toy = toy.groupby("kategori", as_index=False).agg(
    total=("harga", "sum"), jumlah=("id", "nunique")
).sort_values("total", ascending=False)

print("Sesudah diringkas:")
display(ringkasan_toy)

Sebelum diringkas:

  kategori     harga
1        B  275000.0
2        A  250000.0
3        B  300000.0

Sesudah diringkas:

  kategori     total  jumlah
1        B  575000.0       2
0        A  250000.0       1

### Ringkasan 2 dimensi: `pivot_table()`

Data yang sama, cuma disusun ulang jadi tabel kategori × id.

In [8]:
display(pd.pivot_table(toy, values="harga", index="kategori", columns="id", aggfunc="sum", fill_value=0))

id               2         3         4
kategori
A              0.0  250000.0       0.0
B         275000.0       0.0  300000.0

### Filter

Ambil baris yang kategorinya "B" doang.

In [9]:
print("Sebelum, jumlah baris:", toy.shape[0])

hasil_filter = toy[toy["kategori"] == "B"]

print("Sesudah difilter, jumlah baris:", hasil_filter.shape[0])
display(hasil_filter)

Sebelum, jumlah baris: 3
Sesudah difilter, jumlah baris: 2

   id    tanggal kategori     harga
1   2 2026-01-05        B  275000.0
3   4 2026-02-10        B  300000.0

Segitu dulu contoh sederhananya. Sekarang perintah yang sama dipakai ke `data.csv` — dataset asli 133 baris dari pertemuan 3.

## 1. Recap Kondisi Data (Temuan Pertemuan 3)

In [10]:
import pandas as pd

df = pd.read_csv("data.csv")
print(df.shape)
print(df.isna().sum())
print(df.duplicated().sum())

(133, 8)
id_pesanan     0
tanggal        0
nama_produk    0
kategori       0
harga          6
jumlah         0
wilayah        0
modal          0
dtype: int64
3

## 2. Menghapus Baris Duplikat

In [11]:
baris_duplikat = df[df.duplicated(keep=False)].sort_values("id_pesanan")
display(baris_duplikat[["id_pesanan", "nama_produk", "kategori", "harga"]])

     id_pesanan       nama_produk    kategori    harga
28         1029  Keripik Singkong     Makanan  20000.0
130        1029  Keripik Singkong     Makanan  20000.0
70         1071     Buku Motivasi        Buku  68000.0
131        1071     Buku Motivasi        Buku  68000.0
117        1118           Charger  Elektronik  89000.0
132        1118           Charger  Elektronik  89000.0

In [12]:
df = df.drop_duplicates()
print(df.shape)
print(df.duplicated().sum())

(130, 8)
0

## 3. Contoh Kecil `errors="coerce"`

In [13]:
tanggal_kotor = pd.Series(["2026-01-15", "31-02-2026", "2026-03-10", "bukan tanggal"])
print(pd.to_datetime(tanggal_kotor, errors="coerce"))

harga_kotor = pd.Series(["150000", "abc", "220000", "75rb"])
print(pd.to_numeric(harga_kotor, errors="coerce"))

0   2026-01-15
1          NaT
2   2026-03-10
3          NaT
dtype: datetime64[ns]
0    150000.0
1         NaN
2    220000.0
3         NaN
dtype: float64

## 4. Konversi `tanggal` di Data Asli

In [14]:
print(df["tanggal"].dtype)
df["tanggal"] = pd.to_datetime(df["tanggal"], errors="coerce")
print(df["tanggal"].dtype)
print(df["tanggal"].isna().sum())

object
datetime64[ns]
0

## 5. Melihat Baris `harga` Kosong

In [15]:
kosong = df[df["harga"].isna()]
display(kosong[["id_pesanan", "nama_produk", "kategori", "harga"]])

    id_pesanan         nama_produk    kategori  harga
2         1003   Speaker Bluetooth  Elektronik    NaN
15        1016            Keyboard  Elektronik    NaN
44        1045            Keyboard  Elektronik    NaN
73        1074      Notebook Polos        Buku    NaN
79        1080   Speaker Bluetooth  Elektronik    NaN
98        1099  Buku Resep Masakan        Buku    NaN

## 6. Membandingkan Opsi Penanganan (Belum Dieksekusi)

In [16]:
print("Kalau dihapus, shape jadi:", df.dropna(subset=["harga"]).shape)
print("Rata-rata (mean) harga:", df["harga"].mean())

for produk in kosong["nama_produk"].unique():
    median_produk = df[df["nama_produk"] == produk]["harga"].median()
    print(f"Median harga {produk}: {median_produk}")

Kalau dihapus, shape jadi: (124, 8)
Rata-rata (mean) harga: 267725.8064516129
Median harga Speaker Bluetooth: 313000.0
Median harga Keyboard: 234000.0
Median harga Notebook Polos: 14000.0
Median harga Buku Resep Masakan: 57000.0

## 7. Mengisi `harga` dengan Median per Produk

In [17]:
df["harga"] = df["harga"].fillna(df.groupby("nama_produk")["harga"].transform("median"))
print(df["harga"].isna().sum())
display(df.loc[kosong.index, ["id_pesanan", "nama_produk", "harga"]])

0

    id_pesanan         nama_produk     harga
2         1003   Speaker Bluetooth  313000.0
15        1016            Keyboard  234000.0
44        1045            Keyboard  234000.0
73        1074      Notebook Polos   14000.0
79        1080   Speaker Bluetooth  313000.0
98        1099  Buku Resep Masakan   57000.0

## 8. Mendeteksi Outlier dengan Aturan IQR

In [18]:
q1 = df["harga"].quantile(0.25)
q3 = df["harga"].quantile(0.75)
iqr = q3 - q1
batas_bawah = q1 - 1.5 * iqr
batas_atas = q3 + 1.5 * iqr

print("Q1:", q1, "| Q3:", q3, "| IQR:", iqr)
print("Batas bawah:", batas_bawah, "| Batas atas:", batas_atas)

outlier = df[(df["harga"] < batas_bawah) | (df["harga"] > batas_atas)]
display(outlier[["id_pesanan", "nama_produk", "kategori", "harga", "modal"]])

Q1: 41250.0 | Q3: 181250.0 | IQR: 140000.0
Batas bawah: -168750.0 | Batas atas: 391250.0

    id_pesanan            nama_produk    kategori       harga    modal
40        1041        Sepatu Sneakers     Fashion   8900000.0   245000
55        1056  Laptop Gaming (Bonus)  Elektronik  10500000.0  9600000

## 9. Menyelidiki dan Memutuskan

In [19]:
sneakers_lain = df[df["nama_produk"] == "Sepatu Sneakers"]
display(sneakers_lain[["id_pesanan", "harga", "modal"]])

     id_pesanan      harga   modal
31         1032   364000.0  194000
36         1037   329000.0  197000
40         1041  8900000.0  245000
74         1075   375000.0  196000
104        1105   351000.0  262000

In [20]:
df = df[df["id_pesanan"] != 1041]
print(df.shape)

(129, 8)

## 10. Verifikasi Kondisi Akhir

In [21]:
print(df.shape)
print(df.isna().sum())
print(df.duplicated().sum())
print(df.dtypes)

(129, 8)
id_pesanan     0
tanggal        0
nama_produk    0
kategori       0
harga          0
jumlah         0
wilayah        0
modal          0
dtype: int64
0
id_pesanan              int64
tanggal        datetime64[ns]
nama_produk            object
kategori               object
harga                 float64
jumlah                  int64
wilayah                object
modal                   int64
dtype: object

## 11. Membuat Ulang Kolom Turunan

In [22]:
df["nilai_penjualan"] = df["harga"] * df["jumlah"]
df["untung"] = (df["harga"] - df["modal"]) * df["jumlah"]
display(df[["nama_produk", "harga", "modal", "jumlah", "nilai_penjualan", "untung"]].head())

         nama_produk     harga   modal  jumlah  nilai_penjualan    untung
0              Mouse  150000.0   95000       2         300000.0  110000.0
1              Mouse  155000.0  113000       2         310000.0   84000.0
2  Speaker Bluetooth  313000.0  196000       5        1565000.0  585000.0
3        Novel Fiksi   62000.0   39000       2         124000.0   46000.0
4        Matras Yoga  121000.0   71000       5         605000.0  250000.0

## 12. `groupby()` Pertama: Total Penjualan per Kategori

In [23]:
display(df.groupby("kategori")["nilai_penjualan"].sum())

kategori
Buku           3948000.0
Elektronik    44893000.0
Fashion       15775000.0
Makanan        3275000.0
Olahraga       7913000.0
Name: nilai_penjualan, dtype: float64

## 13. `agg()` dan `sort_values()`: Ringkasan Lengkap

In [24]:
ringkasan = (
    df.groupby("kategori", as_index=False)
      .agg(total_penjualan=("nilai_penjualan", "sum"),
           jumlah_transaksi=("id_pesanan", "nunique"),
           rata_harga=("harga", "mean"))
      .sort_values("total_penjualan", ascending=False)
)
display(ringkasan)

     kategori  total_penjualan  jumlah_transaksi     rata_harga
1  Elektronik       44893000.0                24  641916.666667
2     Fashion       15775000.0                27  178592.592593
4    Olahraga        7913000.0                26  103153.846154
0        Buku        3948000.0                29   48413.793103
3     Makanan        3275000.0                23   49956.521739

## 14. EDA 1 — Kategori Penyumbang Penjualan Terbesar

In [25]:
print("Berdasarkan total penjualan:")
display(ringkasan.sort_values("total_penjualan", ascending=False))

print("\nBerdasarkan jumlah transaksi:")
display(ringkasan.sort_values("jumlah_transaksi", ascending=False))

Berdasarkan total penjualan:

     kategori  total_penjualan  jumlah_transaksi     rata_harga
1  Elektronik       44893000.0                24  641916.666667
2     Fashion       15775000.0                27  178592.592593
4    Olahraga        7913000.0                26  103153.846154
0        Buku        3948000.0                29   48413.793103
3     Makanan        3275000.0                23   49956.521739

Berdasarkan jumlah transaksi:

     kategori  total_penjualan  jumlah_transaksi     rata_harga
0        Buku        3948000.0                29   48413.793103
2     Fashion       15775000.0                27  178592.592593
4    Olahraga        7913000.0                26  103153.846154
1  Elektronik       44893000.0                24  641916.666667
3     Makanan        3275000.0                23   49956.521739

## 15. EDA 2 — Tren Penjualan per Bulan

In [26]:
df["bulan"] = df["tanggal"].dt.to_period("M").astype(str)
per_bulan = df.groupby("bulan", as_index=False).agg(
    total_penjualan=("nilai_penjualan", "sum"),
    jumlah_transaksi=("id_pesanan", "nunique"),
)
display(per_bulan)

     bulan  total_penjualan  jumlah_transaksi
0  2026-01       42775000.0                40
1  2026-02       18240000.0                47
2  2026-03       14789000.0                42

## 16. EDA 3 — Wilayah Ramai vs Wilayah Bernilai Tinggi

In [27]:
per_wilayah = df.groupby("wilayah", as_index=False).agg(
    total_penjualan=("nilai_penjualan", "sum"),
    jumlah_transaksi=("id_pesanan", "nunique"),
)
per_wilayah["rata_rata_per_transaksi"] = (
    per_wilayah["total_penjualan"] / per_wilayah["jumlah_transaksi"]
).round(0)
display(per_wilayah.sort_values("jumlah_transaksi", ascending=False))

    wilayah  total_penjualan  jumlah_transaksi  rata_rata_per_transaksi
1   Jakarta       11089000.0                31                 357710.0
4  Surabaya        6620000.0                28                 236429.0
0   Bandung       38743000.0                25                1549720.0
3     Medan       10020000.0                24                 417500.0
2  Karawang        9332000.0                21                 444381.0

## 17. `pivot_table()`: Wilayah × Kategori

In [28]:
pivot = pd.pivot_table(
    df, values="nilai_penjualan", index="wilayah", columns="kategori",
    aggfunc="sum", fill_value=0,
)
display(pivot)

kategori       Buku  Elektronik    Fashion   Makanan   Olahraga
wilayah
Bandung    838000.0  35250000.0  1252000.0  330000.0  1073000.0
Jakarta    404000.0   2374000.0  5747000.0  977000.0  1587000.0
Karawang   346000.0   2041000.0  4468000.0  673000.0  1804000.0
Medan      709000.0   3773000.0  3395000.0  389000.0  1754000.0
Surabaya  1651000.0   1455000.0   913000.0  906000.0  1695000.0

## 18. Cek Kontribusi Satu Baris

In [29]:
laptop = df[df["nama_produk"] == "Laptop Gaming (Bonus)"]
display(laptop[["id_pesanan", "nama_produk", "wilayah", "bulan", "nilai_penjualan"]])

bandung_total = df[df["wilayah"] == "Bandung"]["nilai_penjualan"].sum()
bandung_tanpa_laptop = df[
    (df["wilayah"] == "Bandung") & (df["nama_produk"] != "Laptop Gaming (Bonus)")
]["nilai_penjualan"].sum()
print("Bandung total:", bandung_total, "| tanpa laptop:", bandung_tanpa_laptop)

jan_total = df[df["bulan"] == "2026-01"]["nilai_penjualan"].sum()
jan_tanpa_laptop = df[
    (df["bulan"] == "2026-01") & (df["nama_produk"] != "Laptop Gaming (Bonus)")
]["nilai_penjualan"].sum()
print("Januari total:", jan_total, "| tanpa laptop:", jan_tanpa_laptop)

    id_pesanan            nama_produk  wilayah    bulan  nilai_penjualan
55        1056  Laptop Gaming (Bonus)  Bandung  2026-01       31500000.0

Bandung total: 38743000.0 | tanpa laptop: 7243000.0
Januari total: 42775000.0 | tanpa laptop: 11275000.0

## 19. Menyimpan Data Bersih ke CSV Baru

In [30]:
df_final = df.drop(columns=["bulan"])
df_final.to_csv("data-bersih.csv", index=False)
print("Tersimpan:", df_final.shape)

Tersimpan: (129, 10)

## 20. Latihan Gabungan

In [31]:
print("Kolom numerik:")
print(df.select_dtypes(include="number").columns.tolist())

print("\nJumlah baris kategori Fashion:")
print(df[df["kategori"] == "Fashion"].shape)

print("\nRingkasan total penjualan per kategori, terurut dari terbesar:")
display(df.groupby("kategori", as_index=False)["nilai_penjualan"].sum()
          .sort_values("nilai_penjualan", ascending=False))

Kolom numerik:
['id_pesanan', 'harga', 'jumlah', 'modal', 'nilai_penjualan', 'untung']

Jumlah baris kategori Fashion:
(27, 11)

Ringkasan total penjualan per kategori, terurut dari terbesar:

     kategori  nilai_penjualan
1  Elektronik       44893000.0
2     Fashion       15775000.0
4    Olahraga        7913000.0
0        Buku        3948000.0
3     Makanan        3275000.0

## Selesai

Data sudah dibersihkan (129 baris, 0 kosong, 0 duplikat) dan sudah dijawab 3 pertanyaan EDA lewat `groupby`/`agg`/`pivot_table`. Hasilnya tersimpan di `data-bersih.csv`, dipakai pertemuan 5 untuk visualisasi.